### PR TITLE
Profile

### PR DESCRIPTION
**Pull request by mariomelchor**

### CODE REVIEW

**Comment by saloiofun** [comment]
@mariomelchor the page looks good, is this page intended for editing in the future?

**Comment by mariomelchor** [comment]
@saloiofun Yes this is where you would edit your profile.

**Comment by saloiofun** [comment]
@mariomelchor , I'll put this PR on hold for now. The code is going to change because of the way the user's profile is handled by Redux.

**Comment by mariomelchor** [comment]
@saloiofun can you please review this PR. I changed the code to get profile from Redux

**Pull request merged**
